spring.datasource.url=jdbc:postgresql://localhost:5432/aws_media_uploader_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false


flyway.enabled=true
flyway.locations=classpath:db/migration

jwt.secret=45fa208eef62571c5b7f975c4bf7695d
jwt.expiration=3600000

otp.expiration-minues=60

aws.accessKey=key
aws.secretKey=secret
aws.region=us-east-1
aws.bucketName=aws-media-upload-bucket